### ISSUE TITLE
MAZI glossary definitions

### ISSUE THREAD

**Issue by ileananethood** [mazi-project/guides#11]
C: Community engagement practices D3.2; Conviviality D3.12 D: DIY networking (D3.2; D3.11)
F: FLOSS; Free (D3.12)
K: Knowledge sharing (D3.12)
L: Libre (D3.12)
O: Open/ openness (D3.12)
P: Place; Participation; Process; Personal point of view / perspective in an interdisciplinary discussion; Power relations in participatory processes / interdisciplinary projects (D3.11)
S: Social cohesion; Sustainable living (D3.12)

**Comment by panosnethood** [comment]
Better add these directly to the corresponding Wiki page: https://github.com/mazi-project/guides/wiki/MAZI-Glossary
