### ISSUE TITLE
Update the expert guides for stretch

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/guides#19]
If this is already done, it should be clear on this page that the stretch version is supported: http://nitlab.inf.uth.gr/mazi-guides/writingSD.html

That is replace "default Raspbian operating system" with the actual Raspbian image that the guides correspond to.

**Comment by panosnethood** [comment]
Could someone make clear in the detaled guides linked above for which Rasbian distribution they refer to? @mavridis92 ?

**Comment by haniavis** [comment]
The text now mentions the raspbian stretch version.
