### ISSUE TITLE
setup initial admin password does not work

### ISSUE THREAD

**Issue by denmarkcontrevida2017** [mazi-project/guides#20]
when setting up admin access ,it does not work.

**Comment by dalelicious** [comment]
Follow up question. What is the default username for the admin access?
We already tried using "admin" as the username but unfortunately it doesn't work.

**Comment by panosnethood** [comment]
Hi, the default username is "mazi_admin" and password "1234".

**Comment by dalelicious** [comment]
Thanks a lot! Just saw the updated documentation.

**Comment by deckspace** [comment]
Well it's not a problem we have experienced. During the setup process the
initial page requests entry of existing password 1234 and your chosen
password.. What happened next?

**Comment by deckspace** [comment]
The default username is mazi_admin and password is the one you set

**Comment by dalelicious** [comment]
Yeah. It's just we didn't see the updated documentation, but it's fine now. Thanks
