### ISSUE TITLE
update command copying image for linux

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/guides#7]
Message from commonslab.gr:

The dd command supports progress monitor with the command parameter "status=progress"

There are various places where we have this guideline and it would be nice to update it

**Comment by hellekin** [comment]
You may also send a `USR1` signal to `dd` to show progress. E.g., [from the dd documentation](https://www.gnu.org/software/coreutils/manual/html_node/dd-invocation.html#dd-invocation):
```
# Output stats every second.
while kill -s USR1 $pid 2>/dev/null; do sleep 1; done
```
